# This is a basic workflow to help you get started with Actions

name: triton CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ triton-one-backend ]
  pull_request:
    branches: [ triton-one-backend ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      #- name: docker build react app
      #  run: |
      #    docker build -t react-workflow-frontend:0.1

      - name: 'building and pushing image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
            docker build ./triton-one -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/triton-one-backend:0.1
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/triton-one-backend:0.1
